using System.Text.Json;
using System.Text.Json.Nodes;
using ReactorSim.Core;
using ReactorSim.Game;

// Offline fit: never changes the lattice curve to hide a finite-core discrepancy.
internal static class LiteratureGeometryCalibration
{
    private static readonly JsonSerializerOptions Pretty = new() { WriteIndented = true };
    internal static void Run(string sourcePath, string outputDirectory)
    {
        Directory.CreateDirectory(outputDirectory);
        var source = JsonNode.Parse(File.ReadAllText(sourcePath))!;
        if (source["data_pack_version"]!.GetValue<string>() != "candu6-two-group-diffusion-v1-literature-geometry-v4")
            throw new ArgumentException("Supply the candidate generated by tune_literature_pack.py.", nameof(sourcePath));
        var inventory = SyntheticGameCoreStateV1.CreateAgedPractice(1001);
        var mapping = Require(PracticeLiquidZoneRrsMappingV1.TryCreateCandu6());
        var trials = new List<object>();
        double zoneScale = 1;
        StaticAbsorptionOverlayV1 Overlay(double fill) => Require(StaticAbsorptionOverlayV1.TryCreate(
            "literature-core-fit", mapping.Nodes.Select(n => new StaticAbsorptionOverlayEntryV1(n.Node,
            .0017230342616652234 * fill * zoneScale, .0006892137046660893 * fill * zoneScale))));
        // Bounded search for a playable effective reflector/coupling surrogate.
        foreach (double coupling in new[] { 1.0, 2.0, 4.0, 8.0 })
        {
            var proposal = source.DeepClone();
            foreach (string edge in new[] { "axial_edge_conductance_m2", "transverse_edge_conductance_m2" })
                foreach (string group in new[] { "group1_m2", "group2_m2" })
                    proposal["geometry"]![edge]![group] = source["geometry"]![edge]![group]!.GetValue<double>() * coupling;
            EquilibriumCoreSolverV1 Solver(double boundary)
            {
                proposal["geometry"]!["vacuum_boundary_conductance_m2"]!["group1_m2"] = boundary;
                proposal["geometry"]!["vacuum_boundary_conductance_m2"]!["group2_m2"] = boundary / 2;
                var model = Require(FullCoreDiffusionModelV1.TryCreateCandu6(Require(
                    FullCoreDiffusionDataPackV1.TryLoadJson(proposal.ToJsonString()))));
                return Require(EquilibriumCoreSolverV1.TryCreate(model, inventory.EnumerateBundles(),
                    PracticeGameSessionFactory.PracticeReferenceThermalPowerWatts));
            }
            double boundary = 0;
            for (int zonePass = 0; zonePass < 3; zonePass++)
            {
                double lo = .000001, hi = .05;
                for (int iteration = 0; iteration < 20; iteration++)
                {
                    boundary = (lo + hi) / 2;
                    var trialSolver = Solver(boundary);
                    double k = Require(trialSolver.TrySolveCandidate(inventory.EnumerateBundles(), Overlay(.5))).SpatialSolve.EffectiveK;
                    if (k > 1) lo = boundary; else hi = boundary;
                    if (Math.Abs(k - 1) < 1e-6) break;
                }
                var solver = Solver(boundary);
                var half = Require(solver.TrySolveCandidate(inventory.EnumerateBundles(), Overlay(.5)));
                var empty = Require(solver.TrySolveCandidate(inventory.EnumerateBundles(), Overlay(0)));
                var full = Require(solver.TrySolveCandidate(inventory.EnumerateBundles(), Overlay(1)));
                double worth = 1000 * (1 / full.SpatialSolve.EffectiveK - 1 / empty.SpatialSolve.EffectiveK);
                double peakBundle = half.ShapeNodePowerWatts.Max();
                double peakChannel = half.ShapeNodePowerWatts.Chunk(12).Max(c => c.Sum());
                trials.Add(new { coupling, zonePass, boundary, zoneScale, k = half.SpatialSolve.EffectiveK, worth, peakBundle, peakChannel });
                Console.WriteLine($"coupling={coupling}, boundary={boundary:R}, k={half.SpatialSolve.EffectiveK:F7}, worth={worth:F5}, channel={peakChannel / 1e6:F4}, bundle={peakBundle / 1000:F2}");
                if (Math.Abs(worth - 7) > .005) { zoneScale *= 7 / worth; continue; }
                WriteJson(Path.Combine(outputDirectory, "trials.json"), JsonSerializer.Serialize(trials, Pretty));
                if (Math.Abs(half.SpatialSolve.EffectiveK - 1) > 5e-5 || peakChannel > 7_200_000 || peakBundle > 920_000) break;
                proposal["source_provenance"] = proposal["source_provenance"]!.GetValue<string>() +
                    $"; offline seed-1001 half-fill leakage fit: interior coupling multiplier {coupling:R}, boundary fast {boundary:R} m2, thermal half fast; no lattice production renormalization";
                WriteJson(Path.Combine(outputDirectory, "proposal.json"), proposal.ToJsonString(Pretty));
                WriteJson(Path.Combine(outputDirectory, "fit.json"), JsonSerializer.Serialize(new
                {
                    coupling,
                    boundary,
                    zoneScale,
                    group1Slope = .0017230342616652234 * zoneScale,
                    group2Slope = .0006892137046660893 * zoneScale,
                    trials
                }, Pretty));
                return;
            }
        }
        throw new InvalidOperationException("No candidate met core startup gates; retain candidate for research only.");
    }

    private static T Require<T>(ContractValidationResult<T> result) => result.IsValid
        ? result.Value : throw new InvalidOperationException(result.FirstDiagnostic.ToString());

    // Pack identities hash bytes: match the checked-in Windows-authored artifact
    // even when this offline reproduction is run on another operating system.
    private static void WriteJson(string path, string json) =>
        File.WriteAllText(path, json.Replace("\r\n", "\n", StringComparison.Ordinal)
            .Replace("\n", "\r\n", StringComparison.Ordinal));
}
