<Project>
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <EnableNETAnalyzers>true</EnableNETAnalyzers>
    <AnalysisLevel>10-recommended</AnalysisLevel>
    <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
    <CodeAnalysisTreatWarningsAsErrors>true</CodeAnalysisTreatWarningsAsErrors>
    <DefineConstants Condition="'$(EnableRuntimeProfiling)' == 'true'">$(DefineConstants);RUNTIME_PROFILE</DefineConstants>
    <DefineConstants Condition="'$(EnableCpuParallelism)' == 'true'">$(DefineConstants);CPU_PARALLEL</DefineConstants>
  </PropertyGroup>
</Project>
