import { PROTOCOL_VERSION, createUnavailableRrsSnapshot, type CanduSnapshot } from "./protocol";

export function createSnapshot(): CanduSnapshot {
  const channels = Array.from({ length: 380 }, (_, channelIndex) => ({
    channelIndex,
    gridColumn: channelIndex % 22,
    gridRow: Math.floor(channelIndex / 22),
    flowDirection: "toward-end-a" as const,
    averageBurnupMwdPerKg: 0,
    powerWatts: 1,
    localPowerFraction: 1,
    localTiltFraction: 0,
    xenon: {
      channelIndex,
      meanI135NumberDensityM3: 0,
      maxI135NumberDensityM3: 0,
      meanXe135NumberDensityM3: 0,
      maxXe135NumberDensityM3: 0,
      meanDynamicAbsorptionGroup1PerM: 0,
      maxDynamicAbsorptionGroup1PerM: 0,
      meanDynamicAbsorptionGroup2PerM: 0,
      maxDynamicAbsorptionGroup2PerM: 0,
    },
    bundles: Array.from({ length: 12 }, (_, position) => ({
      position,
      bundleId: `bundle-${channelIndex}-${position}`,
      fuelTypeId: "NAT-U-SYNTHETIC",
      currentBurnupMwdPerKg: 0,
      powerWatts: 1,
      localPowerFraction: 1,
      insertedAtSeconds: 0,
      stateVersion: 0,
      isFresh: true,
      hasFuel: true,
      reflectiveFaces: [],
      group1Flux: 1,
      group2Flux: 1,
    })),
  }));

  return {
    protocol: PROTOCOL_VERSION,
    source: "wasm",
    sequence: 0,
    scenarioId: "test",
    dataPackId: "test",
    simulationTimeSeconds: 0,
    wallElapsedSeconds: 0,
    normalizedPowerFraction: 1,
    targetPowerFraction: 1,
    axialTiltFraction: 0,
    rrsReserveFraction: 1,
    deviceAvailableFraction: 1,
    pendingActionCount: 0,
    scoreTotal: 0,
    scoreDelta: 0,
    isPaused: false,
    playbackModeId: "1x",
    freshBundlesAvailable: 8,
    refuellingOperationCount: 0,
    lastRefuelledChannel: -1,
    lastRefuellingDirectionId: null,
    lastRefuellingShiftCount: 0,
    physics: {
      sourceId: "transport-test",
      formulationId: "transport-test",
      shapeMethodId: "transport-test",
      amplitudeMethodId: "transport-test",
      reactivityMethodId: "transport-test",
      solveState: "converged",
      isAuthoritative: true,
      bindingVersion: 0,
      referencePowerWatts: 1,
      powerAmplitude: 1,
      actualPowerFraction: 1,
      targetPowerWatts: 1,
      totalPowerWatts: 1,
      meanChannelPowerWatts: 1,
      meanBundlePowerWatts: 1,
      effectiveK: 1,
      reactivity: 0,
      weightedPerturbationReactivity: 0,
      reactivityNumerator: 0,
      reactivityDenominator: 1,
      reactivityIdentity: "transport-test",
      reactivityBindingDigestHex: "",
      coreReactivity: 0,
      compensatedNetReactivity: 0,
      compensationState: 0,
      compensationCommand: 0,
      compensationLowerBound: -0.25,
      compensationUpperBound: 0.25,
      compensationSaturated: false,
      compensationResponseTimeSeconds: 4,
      cadenceIdentity: "transport-test",
      powerBalanceRelativeError: 0,
      solverIdentity: "transport-test",
      solverIterationCount: 1,
      solverResidualRelativeInfinity: 0,
    },
    xenon: {
      stateIdentity: "transport-test",
      stateDigestHex: "",
      stateVersion: 0,
      simulationTimeSeconds: 0,
      nodeCount: 0,
      couplingIdentity: "transport-test",
      hasCoupling: false,
      baseCoefficientDigestHex: "",
      dynamicXenonDigestHex: "",
      effectiveCoefficientDigestHex: "",
      meanI135NumberDensityM3: 0,
      maxI135NumberDensityM3: 0,
      meanXe135NumberDensityM3: 0,
      maxXe135NumberDensityM3: 0,
      meanDynamicAbsorptionGroup1PerM: 0,
      maxDynamicAbsorptionGroup1PerM: 0,
      meanDynamicAbsorptionGroup2PerM: 0,
      maxDynamicAbsorptionGroup2PerM: 0,
      selectedChannelIndex: -1,
      selectedChannel: null,
    },
    rrs: createUnavailableRrsSnapshot(),
    core: {
      channelCount: 380,
      bundlePositionCount: 12,
      gridWidth: 22,
      gridHeight: 22,
      channels,
    },
    diagnostics: {
      convergence: {
        state: "converged",
        iterations: 1,
        residual: 0,
        relativePowerError: 0,
        lastSolveMilliseconds: 0,
        solverLabel: "test",
      },
      checks: [],
    },
    lastEvent: null,
  };
}

export function createShift(): NonNullable<CanduSnapshot["shift"]> {
  return { id: "useful-fuel-day-v1", seed: 42, title: "One useful fuel day", objective: "Discharge useful fuel and finish the day.",
    horizonSeconds: 86400, remainingSeconds: 72000, fuelBudget: 128, fuelConsumed: 8,
    usefulBundlesDischarged: 3, usefulBundlesRequired: 8, usefulBurnupThresholdMwdPerKg: 6,
    thermalEnergyMwh: 8256, electricalEnergyMwhEstimate: 2600, dischargeReward: 36,
    freshFuelCost: 12, operatingPoints: 400, outcome: "in-progress", reward: "Efficient refueller badge", rewardEarned: false };
}
